name: Manual test executor
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      mining_trucks_count:
        required: true
        type: number
        description: 'Number of Mining Trucks'
        default: 1
      mining_station_count:
        required: true
        type: number
        description: 'Number of Mining Stations'
        default: 1
      simulation_length:
        required: false
        type: number
        description: 'Simulation length in Minutes'
        default: 4320
      log_level:
        required: false
        type: choice
        description: 'Logging level for the simulation'
        default: info
        options:
        - info
        - debug

jobs:
  build:
    name: Environment Setup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      #########################################################################
      # Environment Setup
      #########################################################################
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update environment
        run: |
            pip install -r dependencies_pip.txt

      #########################################################################
      # Start manual execution
      #########################################################################
      - name: Operation Execution
        run: |
          python start.py -n ${{inputs.mining_trucks_count }} -m ${{inputs.mining_station_count }} -o ${{inputs.simulation_length }} -l ${{inputs.log_level }}
