name: Execute built-in tests
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Environment Setup
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      #########################################################################
      # Environment Setup
      #########################################################################
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Update environment
        run: |
            pip install -r dependencies_pip.txt

      #########################################################################
      # Start the test execution
      #########################################################################
      - name: Test Execution
        run: |
          python run_tests.py
